import sqlite3
conn = sqlite3.connect(r'C:\Users\AC\Desktop\final project\order-fulfillment-coordinator\apps\api\fulfillment.db')
cur = conn.cursor()
cur.execute("SELECT id, customer_email, shipping_zip, shipping_city, status, carrier_id, tracking_number, shipping_cost FROM orders WHERE id LIKE '240e%'")
r = cur.fetchone()
print('ID:', r[0])
print('Email:', r[1])
print('Zip:', r[2])
print('City:', r[3])
print('Status:', r[4])
print('Carrier:', r[5])
print('Tracking:', r[6])
print('Cost:', r[7])
conn.close()
